# Generated by Django 2.2.4 on 2019-10-07 10:41

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('final_fusion', '0003_auto_20190909_1448'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScriptModule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('name', models.CharField(default='Script Module', max_length=40)),
                ('code_content', models.CharField(max_length=900)),
                ('final_fusion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='final_fusion.FinalFusion')),
            ],
        ),
    ]
