# Generated by Django 2.2.4 on 2019-10-08 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('script_module', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scriptmodule',
            name='archived',
            field=models.BooleanField(default=False),
        ),
    ]
