# Generated by Django 2.2.4 on 2019-09-03 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('final_fusion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='finalfusion',
            name='name',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
