# Generated by Django 2.2.4 on 2019-09-09 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('final_fusion', '0002_finalfusion_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finalfusion',
            name='name',
            field=models.CharField(default='Final Fusion', max_length=40),
        ),
    ]
