# Generated by Django 2.2.4 on 2019-09-16 08:25

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('final_fusion', '0003_auto_20190909_1448'),
    ]

    operations = [
        migrations.CreateModel(
            name='RuleModule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('archived', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=100)),
                ('subjects', models.CharField(max_length=200)),
                ('if_conditions', models.CharField(max_length=200)),
                ('then_cases', models.CharField(max_length=200)),
                ('final_fusion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='final_fusion.FinalFusion')),
            ],
        ),
    ]
