# Generated by Django 2.2.4 on 2019-09-16 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rule_module', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rulemodule',
            name='rule_type',
            field=models.CharField(default='col', max_length=10),
            preserve_default=False,
        ),
    ]
