# Generated by Django 2.2.4 on 2019-09-23 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rule_module', '0002_rulemodule_rule_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rulemodule',
            name='subjects',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
