# Generated by Django 2.2.4 on 2019-09-23 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rule_module', '0003_auto_20190923_1254'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rulemodule',
            old_name='subjects',
            new_name='col_subject',
        ),
    ]
