# Generated by Django 2.2.4 on 2019-10-28 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rule_module', '0004_auto_20190923_1319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rulemodule',
            name='if_conditions',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='rulemodule',
            name='then_cases',
            field=models.CharField(max_length=1000),
        ),
    ]
