# Generated by Django 2.2 on 2019-05-03 12:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SecurityToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('code', models.CharField(max_length=60)),
                ('expiration_after_days', models.IntegerField(default=14)),
            ],
        ),
    ]
