# Generated by Django 2.2.3 on 2019-08-12 11:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TQFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('source_file_name', models.CharField(max_length=100)),
                ('display_file_name', models.CharField(max_length=50)),
            ],
        ),
    ]
