# Generated by Django 2.2.3 on 2019-08-26 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tq_file', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tqfile',
            name='content_json',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
