# Generated by Django 2.2.3 on 2019-08-26 13:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_project_archived'),
        ('tq_file', '0002_tqfile_content_json'),
    ]

    operations = [
        migrations.AddField(
            model_name='tqfile',
            name='project',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='project.Project'),
            preserve_default=False,
        ),
    ]
