# Generated by Django 2.2.4 on 2019-08-28 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tq_file', '0003_tqfile_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='tqfile',
            name='archived',
            field=models.BooleanField(default=False),
        ),
    ]
