# Generated by Django 2.2.4 on 2019-09-02 11:27

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('final_fusion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinalFusionColumn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('archived', models.BooleanField(default=False)),
                ('source_column_name', models.CharField(max_length=30)),
                ('display_column_name', models.CharField(max_length=30)),
                ('rows_json', models.TextField(max_length=2000)),
                ('final_fusion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='final_fusion.FinalFusion')),
            ],
        ),
    ]
