# Generated by Django 2.2.4 on 2019-09-03 08:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tq_file', '0004_tqfile_archived'),
        ('final_fusion_column', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='finalfusioncolumn',
            name='source_tq',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tq_file.TQFile'),
        ),
    ]
