# Generated by Django 2.2.4 on 2019-09-25 08:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rule_module', '0004_auto_20190923_1319'),
        ('final_fusion_column', '0002_finalfusioncolumn_source_tq'),
    ]

    operations = [
        migrations.AddField(
            model_name='finalfusioncolumn',
            name='rm_dependency',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='rule_module.RuleModule'),
        ),
    ]
