# Generated by Django 2.2.4 on 2019-10-21 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('final_fusion_column', '0003_finalfusioncolumn_rm_dependency'),
    ]

    operations = [
        migrations.AddField(
            model_name='finalfusioncolumn',
            name='manually_removable',
            field=models.BooleanField(default=False),
        ),
    ]
